### ISSUE TITLE
Gravity Forms

### ISSUE THREAD

**Issue by bfrancey** [chr15m/DoodleCSS#11]
Hey - I was trying to figure out how to add this style to a Gravity Form in Wordpress. I've added the CSS style to the custom CSS, loaded the font through the theme font manager, and have added the class name to the form. Thanks!

**Comment by chr15m** [comment]
I'm sorry, I don't have sufficient information to diagnose the issue you're experiencing. You can use the developer tools inspector to try to figure out why the styles aren't applying. You should check that the CSS is not being cached etc.
