### ISSUE TITLE
Secondary development request 

### ISSUE THREAD

**Issue by myNameIsDu** [chr15m/DoodleCSS#15]
Hey, guys, thanks for you created this creative project,  It's incredible, I used it in my blog in my and so many side projects. 

I love it, But as I use it, I have my own ideas and requirements, such as I prefer white background, I created a modal component, so I had got to override it. so I hope to do a secondary development based on it and release it, would like your permission

**Comment by chr15m** [comment]
Hello @myNameIsDu. Yes, the project is licensed under the MIT license. You can [read the license here](https://github.com/chr15m/DoodleCSS/blob/main/LICENSE). So yes you are free to make your own fork. The only requirement is that you keep the [LICENSE](https://github.com/chr15m/DoodleCSS/blob/main/LICENSE) and copyright intact in your fork.

A link back to the original project is appreciated. Thank you.
