### ISSUE TITLE
iOS Overwrites

### ISSUE THREAD

**Issue by kleinderg** [chr15m/DoodleCSS#4]
Some of the intended css is overwritten in iOS.

![image](https://user-images.githubusercontent.com/33735046/146266450-26fd0c65-f418-4f29-b55d-c985b00b6394.png)
![image](https://user-images.githubusercontent.com/33735046/146266467-31c36c22-51b1-4cf1-a249-242dd1fcfa3f.png)
![image](https://user-images.githubusercontent.com/33735046/146266485-1529f237-7de0-475d-ad9a-77a4b3e3469f.jpeg)

~~Hope this is the right place for this. Love your work!~~

**Comment by chr15m** [comment]
I think #3 should have fixed this, thanks!
