### ISSUE TITLE
introduce some variation

### ISSUE THREAD

**Issue by nnmrts** [chr15m/DoodleCSS#5]
Hey! Saw your post on Reddit and really like this project.

While scrolling through the demo page, I immediately got an idea that could be a nice addition. Currently, when there are multiple elements of the same type next to each other, the "hand-drawn" illusion kind of disappears, because their squiggly outlines look exactly the same.

I didn't take a look at the source code yet but maybe something like this could achieve what I'm talking about:

```css
.outline:nth-of-type(4n) {
	/* style for squiggly line */
}

.outline:nth-of-type(4n+1) {
	/* style for slightly different squiggly line */
}

/*
	and so on...
*/
```

**Comment by chr15m** [comment]
Patches welcome!
