### ISSUE TITLE
HTML headers not included in style sheet

### ISSUE THREAD

**Issue by Artemixed** [chr15m/DoodleCSS#8]
![image](https://user-images.githubusercontent.com/52324254/146857587-91f008c9-82d2-4ae5-b0f4-3c3cea802ecc.png)
Would it perhaps be a possible to add this to the doodle.css? 
It'd be as simple as: 
```
.doodle h1 {
  font-family: 'Short Stack', cursive;
  color: #3c3c3c;
}
```

thanks in advance! ⚡

**Comment by chr15m** [comment]
I would like to leave the choice of font flexible so that people can use other hand written fonts. So I think the best way to go is have your own stylesheet with a `body` style that sets the font like that. Let me know if there is some issue with that approach I am not seeing.

**Comment by Artemixed** [comment]
That's understandable, maybe just including the right color then? Personally I'm a fan of the font! I think it goes well with the style sheet you made but I could see other people maybe not liking the chosen font as much. 

⚡

**Comment by chr15m** [comment]
That colour is already applied to the `h1` tag:

![screenshot](https://user-images.githubusercontent.com/67130/147169720-8c71c05a-f0c5-400f-b3d2-ab9b45d4ad1c.png)

You can verify this using the inspector. From the screenshot you shared it appears your `h1` style is being overridden, perhaps by a different stylesheet.

**Comment by Artemixed** [comment]
I'm sorry, my server aplied a standard style sheet I forgot about that had overwritten the ```doodle.css``` file. My bad... 
My sincere apologies for the false ticket in that case! I wish you all the best~! 

⚡

**Comment by chr15m** [comment]
All good, not a problem.
